// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

/* ======================================================
   IMAGE UPLOAD HELPER (ADMIN ONLY)
   ====================================================== */

export async function uploadImageToCloudinary(
  base64Image: string,
  folder: string = "products"
): Promise<{ url: string; public_id: string }> {
  // 1️⃣ Get session + access token
  const { data, error } = await supabase.auth.getSession();

  if (error || !data.session) {
    throw new Error("User not authenticated");
  }

  const accessToken = data.session.access_token;

  // 2️⃣ Call Supabase Edge Function
  const response = await fetch(
    `${SUPABASE_URL}/functions/v1/upload-image`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify({
        image: base64Image, // MUST include data:image/...;base64,...
        folder,
      }),
    }
  );

  const result = await response.json();

  if (!response.ok) {
    console.error("Upload failed:", result);
    throw new Error(result.error || "Image upload failed");
  }

  return {
    url: result.url,
    public_id: result.public_id,
  };
}
